/*
 * Copyright 2025 ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package tech.pegasys.web3signer.bls.keystore.model;

import tech.pegasys.web3signer.bls.keystore.KeyStoreValidationException;

import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.tuweni.bytes.Bytes;

/**
 * BLS Key Store with Jackson Bindings as per json schema. crypto and version are minimum required
 * fields. pubkey is optional, however, if provided, it is validated against decrypted key.
 * description, uuid and path are not utilized for decryption.
 *
 * @see <a href="https://github.com/ethereum/ercs/blob/master/ERCS/erc-2335.md">EIP-2335</a>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record KeyStoreData(
    @JsonProperty(value = "crypto") Crypto crypto,
    @JsonProperty(value = "path") String path,
    @JsonProperty(value = "uuid") UUID uuid,
    @JsonProperty(value = "version") Integer version,
    @JsonProperty(value = "pubkey") Bytes pubkey,
    @JsonProperty(value = "description") String description) {

  public static final int KEYSTORE_VERSION = 4;

  /**
   * Compact Constructor: Automatically executes validation for BOTH Jackson deserialization and
   * manually invoked constructors.
   */
  public KeyStoreData {
    if (version == null) {
      throw new KeyStoreValidationException("Invalid KeyStore: Missing 'version' property");
    }

    if (crypto == null) {
      throw new KeyStoreValidationException("Invalid KeyStore: Missing 'crypto' property");
    }

    if (version != KEYSTORE_VERSION) {
      throw new KeyStoreValidationException("KeyStore version not supported: " + version);
    }
  }

  /**
   * Overloaded constructor for manual creation. This is safely ignored by Jackson deserialization.
   */
  public KeyStoreData(final Crypto crypto, final Bytes pubkey, final String path) {
    this(crypto, path, UUID.randomUUID(), KEYSTORE_VERSION, pubkey, "Generated by Web3Signer");
  }
}
