---
name: 'build-test'
description: 'Composite action to build and test Web3Signer'
outputs:
  publish-version:
    description: 'The publish version of the build'
    value: ${{ steps.checks-version.outputs.publish-version }}
  specific-version:
    description: 'The specific version of the build'
    value: ${{ steps.checks-version.outputs.specific-version }}
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Print Version
      id: checks-version
      run:  |
        output=$(./gradlew -q printVersion)
        # Extract specific-version and publish-version from the output
        specific_version=$(echo "$output" | grep -oP 'specific-version=\K.*')
        publish_version=$(echo "$output" | grep -oP 'publish-version=\K.*')
        # Set the outputs
        echo "specific-version=$specific_version" >> $GITHUB_OUTPUT
        echo "publish-version=$publish_version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and unit test
      run: ./gradlew build
      shell: bash

    - name: Integration Tests
      run: ./gradlew integrationTest
      shell: bash

    - name: Acceptance Tests
      run: ./gradlew acceptanceTest
      shell: bash

    - name: Build Step Output
      run: echo "<h2>Test Results</h2>" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Summarize tests results
      uses: jeantessier/test-summary-action@v1.0.7
      if: always()

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: '**/build/reports/'
        retention-days: 7