services:
  # see https://docs.localstack.cloud/getting-started/installation/#docker-compose
  # see https://docs.localstack.cloud/references/configuration/
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      # ready hook script configuration
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      #- "./init/ready.d:/etc/localstack/init/ready.d" # ready hooks
      - "${DOCKER_HOST_PATH:-/var/run/docker.sock}:/var/run/docker.sock"