openapi: 3.0.3
info:
  title: 'Web3Signer ETH2 Api'
  description: 'Sign Eth2 Artifacts'
  version: '@VERSION@'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /
  - url: http://localhost:9000/

paths:
  /api/v1/eth2/sign/{identifier}:
    $ref: './signing/paths/sign.yaml'
  /api/v1/eth2/publicKeys:
    $ref: './signing/paths/public_keys.yaml'
  /api/v1/eth2/highWatermark:
    $ref: './signing/paths/high_watermark.yaml'
  /reload:
    $ref: './signing/paths/reload.yaml'
  /upcheck:
    $ref: './signing/paths/upcheck.yaml'
  /healthcheck:
    $ref: './signing/paths/healthcheck.yaml'
  /eth/v1/keystores:
    $ref: './keymanager/paths/keystores.yaml'

externalDocs:
  description: 'Web3Signer User Documentation'
  url: 'https://docs.web3signer.consensys.net/'
