openapi: 3.0.0
info:
  title: 'Web3Signer Filecoin'
  description: 'Upcheck'
  version: '0.2.1-dev-b4a90c7d'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /
  - url: http://localhost:9000/

paths:
  /upcheck:
    get:
      tags:
        - 'Server Status'
      summary: 'Server Status'
      description: 'Web3Signer server status'
      operationId: 'UPCHECK'
      responses:
        '200':
          description: 'OK'
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              example: 'OK'
        '500':
          description: 'Internal Web3Signer server error'

externalDocs:
  description: 'Web3Signer User Documentation'
  url: 'https://doc.web3signer.pegasys.tech/'