---
name: 'test_results'
description: 'Collate test results'

runs:
  using: "composite"
  steps:

    - name: Gather test results
      shell: bash
      run: |
        rm -rf build/test-output
        FILES=`find . -name test-results`
        for FILE in $FILES
        do
          MODULE=`echo "$FILE" | sed -e 's@./\(.*\)/build/test-results@\1@'`
          TARGET="build/test-output/$MODULE"
          mkdir -p "$TARGET"
          cp -rf ${FILE}/*/* "$TARGET"
        done
        ls -la build/test-output/

    - name: Publish Test Results
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: 'build/test-output/'
        summary-report: true
        test-report: true
        test-list-report: true
        failed-report: true
        fail-rate-report: true
        insights-report: true
        slowest-report: true        
      if: always()
