---
name: 'setup-java-gradle'
description: 'Composite action to Setup Java and Gradle for Web3Signer'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4