openapi: 3.0.0
info:
  title: 'Web3Signer Filecoin'
  description: 'Upcheck'
  version: '@VERSION@'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /
  - url: http://localhost:9000/

paths:
  /reload:
    post:
      tags:
        - 'Reload Signer Keys'
      summary: 'Reload signer keys asynchronously'
      description: 'Reload signer keys asynchronously'
      operationId: 'RELOAD'
      responses:
        '200':
          description: 'Call is successful'
        '500':
          description: 'Internal Web3Signer server error'
  /upcheck:
    get:
      tags:
        - 'Server Status'
      summary: 'Server Status'
      description: 'Web3Signer server status'
      operationId: 'UPCHECK'
      responses:
        '200':
          description: 'OK'
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              example: 'OK'
        '500':
          description: 'Internal Web3Signer server error'
  /healthcheck:
    get:
      tags:
        - 'Server Health Status'
      summary: 'Server Health Status'
      description: 'Web3Signer server health status'
      operationId: 'HEALTHCHECK'
      responses:
        '200':
          description: 'System is healthy'
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheck"
        '503':
          description: 'At least one procedure is unhealthy'
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheck"

components:
  schemas:
    HealthCheck:
      type: object
      properties:
        status:
          type: string
          description: 'health status'
        checks:
          type: array
          description: 'list of status checks'
          items:
            properties:
              id:
                type: string
                description: 'status id'
              status:
                type: string
                description: 'health status'
        outcome:
          type: string
          description: 'the overall outcome of health check'

externalDocs:
  description: 'Web3Signer User Documentation'
  url: 'https://docs.web3signer.consensys.net/'
