blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Get Setup Help
    url: https://github.com/Consensys-Incorporated/web3signer/discussions/new?category=q-a
    about: Troubleshooting, configuration, and key storage integration questions.
  - name: Propose a Feature or RFC
    url: https://github.com/Consensys-Incorporated/web3signer/discussions/new?category=ideas
    about: Propose and discuss new features or architectural ideas.
