openapi: 3.0.0
info:
  title: 'Web3Signer'
  description: 'Sign Eth2 Artifacts'
  version: '@VERSION@'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /
  - url: http://localhost:9000/

paths:
  /signer/sign/{identifier}:
    post:
      tags:
        - 'Signing'
      summary: 'Signs data for key'
      description: 'Signs data for the public key specified as part of the URL and returns the signature'
      operationId: 'signForIdentifier'
      parameters:
        - name: 'identifier'
          in: 'path'
          required: true
          description: 'Key for which data to sign'
          schema:
            type: 'string'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                artifactType:
                  type: string
                slot:
                  type: int
                sourceEpoch:
                  type: int
                targeteEpoch:
                  type: int
              required:
                - data
              additionalProperties:
                type: string
            example:
              data: 0x48656c6c6f2c20776f726c6421

      responses:
        '200':
          description: 'hex encoded string of signature'
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              example: '0xb3baa751d0a9132cfe93e4e3d5ff9075111100e3789dca219ade5a24d27e19d16b3353149da1833e9b691bb38634e8dc04469be7032132906c927d7e1a49b414730612877bc6b2810c8f202daf793d1ab0d6b5cb21d52f9e52e883859887a5d9'
        '404':
          description: 'Public Key not found'
        '400':
          description: 'Bad request format'
        '500':
          description: 'Internal Web3Signer server error'

  /signer/publicKeys/{keyType}:
    get:
      tags:
        - 'Public Key'
      summary: 'List of available Public Keys'
      description: 'Returns the public keys for the private keys that have been loaded into Web3Signer'
      operationId: 'getPublicKeys'
      parameters:
        - name: 'keyType'
          in: 'path'
          required: true
          description: 'Type of public keys to return'
          schema:
            type: string
            enum:
              - BLS
              - SECP256K1
      responses:
        '200':
          description: 'list of public keys'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: 'Bad request format'
        '500':
          description: 'Internal Web3Signer server error'

  /upcheck:
    get:
      tags:
        - 'Server Status'
      summary: 'Server Status'
      description: 'Web3Signer server status'
      operationId: 'upcheck'
      responses:
        '200':
          description: 'OK'
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              example: 'OK'
        '500':
          description: 'Internal Web3Signer server error'

externalDocs:
  description: 'Web3Signer User Documentation'
  url: 'https://doc.web3signer.pegasys.tech/'