---
name: 'test_reports'
description: 'Collate test reports'

runs:
  using: "composite"
  steps:
  
    - name: Gather test reports
      shell: bash
      run: |
        rm -rf build/test-reports
        FILES=`find . -name reports -not -path './build/reports'`
        for FILE in $FILES
        do
          MODULE=`echo "$FILE" | sed -e 's@./\(.*\)/build/reports@\1@'`
          TARGET="build/test-reports/$MODULE"
          SOURCE="${FILE}/tests/test"
          mkdir -p "$TARGET"
          if [[ -d "$SOURCE" ]]; then
            cp -rf "$SOURCE" "$TARGET"
          fi
        done
        if [[ -f 'build/reports/dependency-check-report.html' ]]; then
          cp 'build/reports/dependency-check-report.html' 'build/test-reports'
        fi
        ls -la build/test-reports/

    - name: Publish Test Reports
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: 'build/test-reports/'
        summary-report: true
        test-report: true
        test-list-report: true
        failed-report: true
        fail-rate-report: true
        insights-report: true
        slowest-report: true        
      if: always()

        