name: CI

on:
  push:
    branches:
      # - main
      - gha
  pull_request:

jobs:
  build:
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: dev
    env:
      JAVA_TOOL_OPTIONS: -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Xmx2048m

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and unit test
        run: |
          ./gradlew build

      - name: Integration Test
        run: |
          ./gradlew integrationTest

      # - capture_test_results
      # - capture_test_reports

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            ./
            !./.git/**

  acceptanceTests:
    needs: build
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: dev
    env:
      JAVA_TOOL_OPTIONS: -Xmx4096m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Xmx4096m

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Acceptance Tests
        run: |
          if [ -n "$GCP_SERVICE_KEY" ]; then
            echo "$GCP_SERVICE_KEY" | base64 --decode > $HOME/gcp_service_key.json
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_service_key.json
          fi
          ./gradlew clean installDist
          ./gradlew acceptanceTest
      # - capture_test_results
      # - capture_test_reports
