name: CI

on:
  push:
    branches:
      # - main
      - gha
  pull_request:

env:
  JAVA_TOOL_OPTIONS: -Xmx4096m
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Xmx4096m

jobs:
  build:
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build and unit test
        run: |
          ./gradlew build

      - name: Integration Test
        run: |
          ./gradlew integrationTest

      - name: Test results and report
        uses: ./.github/actions/testResultsReports
        with:
          suiteName: 'unitIntegrationTests'

      - name: Upload workspace build
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            ./build
          retention-days: 7

  acceptanceTests:
    needs: build
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Download workspace build
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Acceptance Tests
        run: |
          if [ -n "$GCP_SERVICE_KEY" ]; then
            echo "$GCP_SERVICE_KEY" | base64 --decode > $HOME/gcp_service_key.json
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_service_key.json
          fi
          ./gradlew clean installDist
          ./gradlew acceptanceTest

      - name: Test results and report
        uses: ./.github/actions/testResultsReports
        with:
          suiteName: 'acceptanceTests'

  depScan:
    needs: build
    runs-on: ubuntu-24.04
    environment: dev    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Download workspace build
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Dependency vulnerability scan
        run: |
          ./gradlew --no-daemon --info dependencyCheckAggregate -DnvdApiDelay=6000

      - name: Test results and report
        uses: ./.github/actions/testResultsReports
        with:
          suiteName: 'dependencyVulnScan'

  buildDocker:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare
        id: prepare
        uses: ./.github/actions/prepare         

      - name: Download workspace build
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Build and test docker image
        run: |
          ./gradlew "-Pbranch=${GITHUB_REF##*/}" testDocker

  publishOpenApiSpec:
    # needs: acceptanceTests
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: '.openapidoc/package-lock.json'
          # cache: 'npm'
      
      # - name: Download workspace build
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: workspace

  #     - add_ssh_keys:
  #         fingerprints:
  #           - "8c:7f:3d:66:05:d9:12:a2:af:58:59:bf:97:c1:c7:84"

      - name: Build openapidoc
        run: |
          cd .openapidoc
          npm ci
          OA_GIT_USERNAME="${GITHUB_ACTOR}" OA_GIT_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com" OA_GIT_URL="${GITHUB_REPOSITORY}" OA_GH_PAGES_BRANCH="gh-pages" node publish.js



