name: CI (Main Branch and Tags)

on:
  push:
    branches:
      - master
      - gha # For testing
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+(-?.*)'

jobs:
  build:
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: production
    outputs:
      publish-version: ${{ steps.build-test.outputs.publish-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          fetch-tags: true

      - name: Build and Test
        id: build-test
        uses: ./.github/actions/build-test

      - name: Create zip and tar distributions
        run: ./gradlew distTar distZip

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: build/distributions/
          retention-days: 1
          if-no-files-found: error

  docker:
    runs-on: ubuntu-24.04
    needs: build
    environment: docker
    # For testing - TODO: Remove
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          fetch-tags: true

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ vars.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            driver-opts: network=host # TODO: Remove once testing is complete

      - uses: actions/download-artifact@v4
        with:
          name: distribution
          path: build/distributions/

      - name: Calculate Docker Tags
        id: calculate-tags
        run: |
          TAGS="localhost:5000/consensys/web3signer:${{ needs.build.outputs.publish-version }}"
          if [ "${{ needs.build.outputs.publish-version }}" != "develop" ]; then
            TAGS="$TAGS,localhost:5000/consensys/web3signer:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and export to docker
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          build-args: |
            TAR_FILE=./build/distributions/web3signer-${{ needs.build.outputs.publish-version }}.tar.gz
          no-cache: true
          load: true
          tags: consensys/web3signer:test

      # TODO: Test docker image
      - name: List Docker Images
        run: |
          docker images
          docker image inspect consensys/web3signer:test

      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          context: .
          build-args: |
            TAR_FILE=./build/distributions/web3signer-${{ needs.build.outputs.publish-version }}.tar.gz
          push: true
          tags: ${{ steps.calculate-tags.outputs.tags }}

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/consensys/web3signer:develop
