name: CI (Main Branch and Tags)

on:
  push:
    branches:
      - master
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+(-?.*)'

jobs:
  build:
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          fetch-tags: true

      - name: Build and Test
        id: build-test
        uses: ./.github/actions/build-test

      - name: Create zip and tar distributions
        run: ./gradlew distTar distZip

      # TODO: Attach distTar as artifact (lowest retention) so that it is available for docker and release jobs
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: build/distributions/
          retention-days: 1
          if-no-files-found: error


       # TODO: Test docker image

       # TODO: Publish Docker image - develop for merges to master, tags/latest for tags

  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/download-artifact@v4
        with:
          name: distribution
          path: build/distributions/

      - name: Display build distributions
        run: ls -l build/distributions/

      - name: Prepair Docker Platfor Pair
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Build and test docker image
        run: |
          ./gradlew "-Pbranch=${GITHUB_REF##*/}" testDocker

      - name: Upload Docker image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/consensys/web3signer:${GITHUB_REF##*/}
          docker push ghcr.io/consensys/web3signer:${GITHUB_REF##*/}


