name: CI (Pull Requests)

on:
  pull_request:

jobs:
  build:
    # 4 cpu, 16G ram
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          fetch-tags: true

      - name: Build And Test
        uses: ./.github/actions/build-test
