name: trivy-vuln-scan
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 8 * * *'

jobs:
  trivy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build and test docker image
        run: |
          ./gradlew "-Pbranch=${GITHUB_REF##*/}" testDocker

      - name: Vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: consensys/web3signer:develop-jdk21
          format: sarif
          output: 'trivy-results.sarif'

      # Check the vulnerabilities via GitHub security tab
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'